#!/usr/bin/perl
open(OUT,">R_script_viz.r");
print OUT "library(RSQLite)\n";
print OUT "con <- dbConnect(dbDriver(\"SQLite\"), dbname = \"$ARGV[0]\.sq3\")\n";
print OUT "dbListTables(con)\n";
print OUT "dbReadTable(con,\"iperf_transfer\")\n";
print OUT "mydata <- dbGetQuery(con, \"select oml_sender_id,begin_interval,size,end_interval from iperf_transfer where oml_sender_id=1\")\n";
print OUT "intervals <- mydata\$end_interval - mydata\$begin_interval\n";
print OUT "throughput <- abs(mydata\$size)/intervals/1024/1024*8\n";
print OUT "pdf(\"$ARGV[0]1\.pdf\")\n";
print OUT "plot(throughput,type=\"o\",col=\"red\",xlab=\"Experiment Interval\",ylab=\"Throughput (Mbps)\")\n";
print OUT "title(main=\"Iperf_Experiment of IP_address 192\.168\.3\.12\", col.main=\"blue\", font.main=4)\n";
print OUT "mydata <- dbGetQuery(con, \"select oml_sender_id,begin_interval,size,end_interval from iperf_transfer where oml_sender_id=2\")\n";
print OUT "intervals <- mydata\$end_interval - mydata\$begin_interval\n";
print OUT "throughput <- abs(mydata\$size)/intervals/1024/1024*8\n";
print OUT "pdf(\"$ARGV[0]2\.pdf\")\n";
print OUT "plot(throughput,type=\"o\",col=\"blue\",xlab=\"Experiment Interval\",ylab=\"Throughput (Mbps)\")\n";
print OUT "title(main=\"Iperf_Experiment of IP_address 192\.168\.2\.12\", col.main=\"red\", font.main=4)\n";
print OUT "dev.off()";
close OUT;
